name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3:latest

    strategy:
      matrix:
        php-versions: ['8.4']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql, sqlite3, pdo_sqlite
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Install Playwright
      run: |
        npm install playwright
        npx playwright install --with-deps

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate --ansi
        touch database/database.sqlite
        php artisan migrate --env=testing

    - name: Run Laravel Pint (Code Style)
      run: vendor/bin/pint --test

    - name: Run Pest Tests with Coverage
      run: php artisan test --parallel --coverage --min=80